import validador as v
import edad as d

print('Clinica el ornitorrinco feliz')
print('Rellene la ficha de la mascota')
print()
print('Nombre:')
name =  input()
print()
print('Especie:')
especie = input()
print()
print('Raza:')
raza = input()
print()
print('Sexo (M/F):')
xsexo = input()
sexo = v.sexo(xsexo)
print()
print ('Fecha de nacimiento (dd/mm/yyyy:')
fecha = input()
fechaNacimiento = v.nacimiento(fecha)
print()
print('número de PET PASSPORT')
passport = input()
mypasaporte = v.passport(passport)

edad = d.edad(fechaNacimiento)
fedad = d.formatoEdad(fechaNacimiento)
print()
print()
print('----------------------------------------------------')
print()
print()
print('Clinica el ornitorrinco feliz')
print('=============================')
print()
print('Nombre:',name)
print('Especie:', especie)
print('Raza:', raza)
print('Sexo: ', sexo)
print ('Fecha de nacimiento:',fedad )
print('número de PET PASSPORT: ',mypasaporte)
print('Edad: ',edad)

